name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install target
      run: rustup target add i686-pc-windows-msvc

    - name: Build
      run: cargo build --release --target i686-pc-windows-msvc --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dinput8.dll
        path: target/i686-pc-windows-msvc/release/dinput8.dll
